ARG IMAGE=opensuse/leap:latest
FROM $IMAGE
COPY . /vlc-bittorrent
WORKDIR /vlc-bittorrent
RUN zypper update -y && \
    zypper install -y autoconf \
                      autoconf-archive \
                      automake \
                      clang \
                      diffutils \
                      file \
                      gcc \
                      libboost_system*-devel \
                      libtool \
                      libtorrent-rasterbar-devel \
                      make \
                      vlc-devel
CMD autoreconf -i && \
    ./configure --with-tests && \
    make && \
    (make check || (cat test/*.log && false))
