#!/usr/bin/env sh
# Copyright 2018 Johan Gunnarsson <johan.gunnarsson@gmail.com>
#
# This file is part of vlc-bittorrent.
#
# vlc-bittorrent is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# vlc-bittorrent is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with vlc-bittorrent.  If not, see <http://www.gnu.org/licenses/>.

git clone --depth 1 https://git.videolan.org/git/vlc/${1:-vlc}.git vlc &&
cd vlc &&
./bootstrap &&
./configure --prefix="${2:-/tmp}" \
            --enable-debug \
            --disable-lua \
            --disable-avcodec \
            --disable-swscale \
            --disable-a52 \
            --disable-xcb \
            --disable-wayland \
            --disable-alsa \
            --disable-chromecast \
            --disable-nls \
            --disable-sparkle &&
make &&
make install
