name: vlc-bittorrent CI

permissions:
  contents: read

on:
  push:
    branches: ['**']
  pull_request:
    branches:
      - master
  schedule:
    # Every Sunday evening
    - cron: '00 22 * * 0'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: 'Ubuntu (${{ matrix.image }})'
    timeout-minutes: 20

    strategy:
      matrix:
        image:
          - 'ubuntu:latest'
          - 'ubuntu:rolling'
          - 'ubuntu:devel'
      fail-fast: false

    container:
      image: ${{ matrix.image }}

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Install dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt-get update
        apt-get -y install autoconf autoconf-archive automake build-essential libtool libtorrent-rasterbar-dev libvlccore-dev libvlc-dev vlc

    - name: Build
      run: |
        autoreconf -i
        ./configure --with-tests
        make

    - name: Test
      run: |
        make check || (cat test/*.log test/data/*.log && false)

  msys2-ucrt64:
    runs-on: windows-latest
    timeout-minutes: 45
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up MSYS2 and install dependencies
        id: msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          release: false
          update: false
          install: >-
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-diffutils
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-libtorrent-rasterbar
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-pkgconf
            mingw-w64-ucrt-x86_64-vlc

      # Patch libtorrent-rasterbar.pc because it contains a hardcoded include path that confuses MSYS2's pkg-config
      - name: Patch libtorrent-rasterbar.pc
        run: |
          sed -i 's|-I/ucrt64|-I${prefix}|g' /ucrt64/lib/pkgconfig/libtorrent-rasterbar.pc

      - name: Build
        run: |
          cmake -B build
          cmake --build build -v

      - name: Test
        run: |
          ctest --test-dir build -V
